eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:9090/eureka}
      
okta:
  oauth2:
    issuer: https://dev-52313690.okta.com/oauth2/default
    audience: api://default
